version: 2
references:
  container_config: &container_config
    docker:
      - image: electronuserland/builder:wine-chrome
        environment:
          TARGET_ARCH: x64
    working_directory: ~/neon-wallet

  workspace_root: &workspace_root
    ~/neon-wallet

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: neon-wallet-{{ checksum "yarn.lock" }}
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install libusb-1.0-0-dev
      - run: yarn
      - run: yarn lint
      - run: yarn flow
      - run: yarn dist
      - save_cache:
          key: neon-wallet-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/*
  test:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: neon-wallet-{{ checksum "yarn.lock" }}
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install libusb-1.0-0-dev
      - run: yarn test
      - run:
          name: Running Xvfb for e2e test
          command: Xvfb -ac :99 -screen 0 1280x1024x16
          background: true
      - run:
          name: Run e2e tests
          command: |
            yarn
            yarn assets
            export DISPLAY=:99
            yarn test:e2e
    store_artifacts:
      - path: artifacts/
      - destination: yarnpkg

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
